### ISSUE TITLE
I have a problem with my script, and I would like to know if I can solve it using the add-on asset manager.

### ISSUE THREAD

**Issue by pybot-1** [hgiesel/anki_script_manager#14]
I instantiated a shortcut key that performs a function, in front of the card, it happens that during the revisions, each card that passes, apparently, ANKI replicates the script, and instead of executing the function once, when I press the shortcut, it execute it twice, on the second letter, three times on the third and so on, until I open the edition and come back, then he restarts the script.

note: my native language is not english, i am sorry if the texts are difficult to understand.

**Comment by pybot-1** [comment]
I noticed that in asset management, the effect is the opposite, when the script is injected by the options "Position: Body" or "Position: Head", during a review, the script is only loaded on the first card, on the following, the script appears in the DOM, but does not perform functions.

**Comment by hgiesel** [comment]
The Anki webview is reused a lot during review, however the template code is always reinserted and freshly executed.
To know whether a specific function was already on this webview, you could test for a global variable:

```js
if (!globalThis._myVariable) {
    // your code

    globalThis._myVariable = true
}
```

**Comment by pybot-1** [comment]
There were 4 rules that I should have followed.
1- Do not instantiate functions within the HTML TAGs, do this by script using the ".on" function.
2- Inject the Script in Tags that do not change when changing the card / note type / front / back, the ideal is to insert it in <Head>.
3- Place an if condition to check if the script is already inserted, if yes, do not reinsert, if not, do the insertion.
4- If possible, avoid global variables.

Thanks for the feedback!
I am loving asset maneger.
