### ISSUE TITLE
Add-on no longer works on Anki 2.1.42

### ISSUE THREAD

**Issue by ValerxTycom** [hgiesel/anki_script_manager#22]
With the latest version of Anki it might seem to not work properly. 
![image](https://user-images.githubusercontent.com/73999527/111979244-1c403780-8b05-11eb-8846-3b61a5837862.png)

**Comment by hgiesel** [comment]
Are you sure you triggered an update. I have an extra version for 2.1.42+ (updated 2021-03-12).

**Comment by ValerxTycom** [comment]
Dear @hgiesel , I've deleted and reinstalled the add-on and it worked perfectly fine. I hope that at least this could be treated as a workaround for some users having the same issue. 
Thanks for your reply
