### ISSUE TITLE
The script I installed via this addon did not work on AnkiDroid for me

### ISSUE THREAD

**Issue by Andrej-Adamenko** [hgiesel/anki_script_manager#5]
Was it supposed to?

**Comment by hgiesel** [comment]
Which script are you exactly talking about?
So it worked on AnkiDesktop, but it did not work on AnkiDroid? That seems to imply that you use some JavaScript feature which doesn't work on Android.

Also, did it throw an error on AnkiDroid, or simply "do nothing"?

**Comment by Andrej-Adamenko** [comment]
I have a small script of my own which was used on both Front and Back sides of cards. The script worked in both Anki versions: Windows Desktop version and AnkiDroid. I decided to use the add-on to avoid duplication of the script. So I removed the script from my templates and installed it there again via Asset Manager. After this operation it worked in Windows, but stopped working in Android. It did not throw any errors, it seemed to be doing nothing after the modification. I suppose it should have been expected, because the Add-on works in a way that the scripts installed via it would work only in Windows Anki and not in Android. I just wanted to confirm that.

This is the code of my script:
```
<script>
function sendFeedback()
{
    var yourMessage = "\n\nТекст вопроса: " + document.getElementById("clozetext").innerHTML;
    var subject = "comment to note #" + document.getElementById("noteid").textContent;
    document.location.href = "mailto:my.email@gmail.com?subject="
        + encodeURIComponent(subject)
        + "&body=" + encodeURIComponent(yourMessage);
}
</script>
```

**Comment by hgiesel** [comment]
![image](https://user-images.githubusercontent.com/7188844/93370636-6b08ce00-f851-11ea-8768-d32f6cf05238.png)

There is an option called "Position" under "Insertion". You want to change this to "Into Template". This is the only insertion position, that works with AnkiMobile/AnkiDroid.

**Comment by Andrej-Adamenko** [comment]
I tested it and confirm that it works on both Android and Windows if it is used as recommended above.
