### ISSUE TITLE
Too many clicks in script development cycle (enhancement)

### ISSUE THREAD

**Issue by Andrej-Adamenko** [hgiesel/anki_script_manager#7]
If it is possible, when I noticed a problem with my script in Card Templates or card preview window I would like to be able to modify my script easily, without having to do many clicks, like switching to another window, opening several other windows, clicking both "Save" and "Write into templates" buttons, etc. I after I modified the script, I would like to be able to easily return to same Card Template or Preview window to test my changes. 

Currently if I understand correctly,  the only way to do it is "Manage note types"->Assets and then I have to click two "save" buttons, then re-open the window and click "Write to templates" button, and then go find my original window.

**Comment by hgiesel** [comment]
What do you think about a shortcut that leads from the Editor (present in AddCards / EditCurrentCard / Browser) that leads to the same window, similiar to how the "Fields..." and "Cards..." buttons are present there?

**Comment by Andrej-Adamenko** [comment]
I am sorry for a very late answer. A shortcut could help. 

I also have another idea which if could be implemented, would help even more... When I changed one of the copies of the script, it should automatically update all other copies (perhaps optionally asking my confirmation for that).

**Comment by hgiesel** [comment]
What do you mean by "copy of the script"? Where are those other copies?

**Comment by Andrej-Adamenko** [comment]
This is one copy:
![image](https://user-images.githubusercontent.com/70955223/94922452-ea89d480-04c2-11eb-80e7-17e72c48427e.png)

This is another copy:
![image](https://user-images.githubusercontent.com/70955223/94922616-38064180-04c3-11eb-9248-23565a04eac7.png)

And this is yet another one:
![image](https://user-images.githubusercontent.com/70955223/94922737-6d129400-04c3-11eb-894b-afb9045edcf6.png)


I would like to edit for example the copy in the Front Template directly and when I close the window I would like the changes to propagate to the copy in the Back Template and to the copy in "Assets"

**Comment by hgiesel** [comment]
Hm, I think of being able to edit the template, without the changes being applied to the Assets as a feature, because it allows you to "try" something out, and if you break it, you can simply revert to the version in the Assets (and write to your card templates).
Also there are some versions, where this wouldn't be possible: Like you change a script that is read-only (because maybe it stems from another add-on, like Closet, etc.)

>  I have to click two "save" buttons, then re-open the window and click "Write to templates" button

I think there's a misunderstanding here in the opening comment. "Write to templates" also Saves. You don't need to open the dialog twice. "Write to templates" does the same as "Save" and **then** writes to the template.

I can facilitate your use case by adding a shortcut to the Assets menu from the card browser (or possibly add another button in the card browser). How does this sound?

**Comment by hgiesel** [comment]
I've created a PR which faciliates implementing this feature: https://github.com/ankitects/anki/pull/781.
If it is merged, I will enable a new button next to "Fields..." and "Cards...", which will be called "Assets...".

**Comment by Andrej-Adamenko** [comment]
There may still be a misunderstanding. I imagined this synchronization I suggested as an optional one. It would not synchronize them in real time. Only when the window is closed or you switch to another template, a Yes/No question would pop up with an additional check box "do not ask again", and perhaps with one more checkbox "use an external merge tool for synchronization". 

So you still would be able to change the code in the template without the synchronization to try something out.

**Comment by hgiesel** [comment]
There are too many scenarios here to consider that I can say that it's worth it, compared to simply a link to the Assets dialog.

1. What if you alter a read-only script
1. What if you delete a non-deleteable script
1. It is generally impossible to reverse the insertion mechanism of meta scripts (scripts which are added through other add-ons)
1. Which means, how do you communicate to the user, that some of them are changeable and some are not? This creates utter confusion.

With the introduction of the `HTML template` section of Asset Manager, this would become even more complex. All-in-all, the development process would not be worth it, compared to what you would gain.

**Comment by hgiesel** [comment]
This is now tracked in #17
