### ISSUE TITLE
Having issues:

### ISSUE THREAD

**Issue by DoctorToBeIn23** [hgiesel/anki_script_manager#8]
I watched the youtube video: https://www.youtube.com/watch?v=9o7uriyIKnw
And I am able to get the multiple choice cards to work if I follow your steps, the problem is when I export them and open it in a new profile it looks like this:
![image](https://user-images.githubusercontent.com/60248099/95399450-789bfb80-08c5-11eb-92bc-7cea8dd08695.png)
What is weird is I exported and airdropped it to a friend and they could open it up and have it look normal. But like I said if I try to import it on my own computer to another profile it doesn't work...

**Comment by hgiesel** [comment]
Could you try installing the [AnkiWebView Inspector](https://ankiweb.net/shared/info/31746032)? After you install it, you can right click the card, and click "Inspect". That way, we might be able to have a look at the error message.

**Comment by DoctorToBeIn23** [comment]
Here is one of the card that was giving me trouble. I will also do the
AnkiWebView when I get a minute!

https://drive.google.com/file/d/1ctKV7ORfh_485QYxTAZILfHLE4buzSr6/view?usp=sharing

**Comment by DoctorToBeIn23** [comment]
I got the add on not sure what you want me to send you?

![image](https://user-images.githubusercontent.com/60248099/95471093-c9036f80-093e-11eb-8a21-48af147669e9.png)

**Comment by hgiesel** [comment]
The problem is that the Closet source code is not the media folder. You need to go into "Tools > Manage Note Types > Assets", and use "Write to Template" again.
This will put the Closet source code into the media folder again, where the Card template can find it.

**Comment by DoctorToBeIn23** [comment]
So after I make cards to be able to share them with others will they need
any of these add ons and or will they need to be on anki 2.1.31 or later
since closet says "Anki >=2.1.31"
[image: image.png]

>

**Comment by DoctorToBeIn23** [comment]
I think I got the hang of it now. One last thing is there a short cut to
"cloze" a card but adding the "[[mc0::]]" ?

**Comment by hgiesel** [comment]
Use [the Custom styles add-on](https://ankiweb.net/shared/info/1899278645). I also talk about it in the video at 44:47. You can create all the "text wrapper" shortcuts you want.

**Comment by hgiesel** [comment]
> So after I make cards to be able to share them with others will they need
any of these add ons and or will they need to be on anki 2.1.31 or later
since closet says "Anki >=2.1.31"

They don't need to, Anki should bring all the files which are rerenced in the notes and card types. Just make sure to check "Include media" checkbox when exporting. In this case the Closet script will be handled as media (because it in an external file).

**Comment by DoctorToBeIn23** [comment]
Thank you I did watch the video but I didn't catch that part. This is such
an amazing contribution to Anki thank you so much!!!
